# Generated by Django 3.1.4 on 2021-05-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questiontype', models.CharField(max_length=255)),
                ('questiondescription', models.CharField(max_length=255)),
            ],
        ),
    ]
