# Generated by Django 3.1.4 on 2021-05-24 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviewapp', '0003_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='qtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interviewapp.topics'),
        ),
    ]
