# Generated by Django 3.1.4 on 2021-07-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewapp', '0004_question_qtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='questionlink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
