# Generated by Django 3.1.4 on 2021-07-16 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviewapp', '0007_auto_20210713_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofperson', models.CharField(max_length=255)),
                ('nameofcollege', models.CharField(max_length=255)),
                ('typeofrole', models.CharField(max_length=255)),
                ('companyexp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interviewapp.company')),
            ],
        ),
    ]
