# Generated by Django 3.1.4 on 2021-07-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewapp', '0008_company_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='experience',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
